# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
    builder: html
    configuration: doc/src/conf.py
    fail_on_warning: true

python:
    install:
        - method: pip
          path: ./python
          extra_requirements:
              - docs

build:
    os: ubuntu-22.04
    tools:
        python: "3.8"
